version: "3.2"
services:
  postgres:
    image: "postgres"
    container_name: "postgres"
    env_file:
      - ./service/.env
    ports:
      - "5432:5432"
    # volumes:
     # - ./postgres:/var/lib/postgresql/data

  api:
    image: dpinedaj/enc-fastapi:1.0.0
    build: .
    container_name: "api"
    env_file:
      - ./service/.env
    ports:
      - "8080:8080"
